/*
 * generated by Xtext
 */
package edu.cmu.sei.annex.dmpl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import edu.cmu.sei.annex.dmpl.services.DmplGrammarAccess;

public class DmplParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DmplGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected edu.cmu.sei.annex.dmpl.parser.antlr.internal.InternalDmplParser createParser(XtextTokenStream stream) {
		return new edu.cmu.sei.annex.dmpl.parser.antlr.internal.InternalDmplParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public DmplGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DmplGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
