/*
 * generated by Xtext
 */
package edu.cmu.sei.annex.dmpl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DmplAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("edu/cmu/sei/annex/dmpl/parser/antlr/internal/InternalDmpl.tokens");
	}
}
