/*
 * generated by Xtext
 */
package edu.cmu.sei.annex.dmpl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DmplUiModule extends edu.cmu.sei.annex.dmpl.ui.AbstractDmplUiModule {
	public DmplUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
