/*
 * generated by Xtext
 */
package edu.cmu.sei.annex.dmpl.ui.contentassist

import edu.cmu.sei.annex.dmpl.ui.contentassist.AbstractDmplProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DmplProposalProvider extends AbstractDmplProposalProvider {
}
