/*
 * generated by Xtext
 */
package edu.cmu.sei.annex.dmpl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DmplRuntimeModule extends edu.cmu.sei.annex.dmpl.AbstractDmplRuntimeModule {

}
