/*
 * generated by Xtext
 */
package edu.cmu.sei.annex.dmpl;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.parsetree.reconstr.ITransientValueService;
import org.eclipse.xtext.serializer.ISerializer;

import edu.cmu.sei.annex.dmpl.conversion.DmplValueConverterService;
import edu.cmu.sei.annex.dmpl.serializer.DmplSerializer;
import edu.cmu.sei.annex.dmpl.serializer.DmplTransientValueService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DmplRuntimeModule extends edu.cmu.sei.annex.dmpl.AbstractDmplRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return DmplValueConverterService.class;
	}
	
	@Override
	public Class<? extends ISerializer> bindISerializer() {
		return DmplSerializer.class;
	}
	
	@Override
	public Class<? extends ITransientValueService> bindITransientValueService() {
		return DmplTransientValueService.class;
	}
}