/*
 * generated by Xtext
 */
package edu.cmu.sei.annex.dmpl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DmplStandaloneSetup extends DmplStandaloneSetupGenerated{

	public static void doSetup() {
		new DmplStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

